spring:

  application:
    name: ms-usuarios

  flyway:
    locations: classpath:migration

  datasource:
    url: jdbc:postgresql://db-usuarios:5432/usuarios
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: 8083
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html


eureka:
  client:
    service-url:
      defaultZone: http://ms-discovery:8761/eureka/
    instance:
      prefer-ip-address: true