spring:
  application:
    name: ms-livros

  flyway:
    locations: classpath:migration

  datasource:
      url: jdbc:postgresql://localhost:5433/usuarios
      username: root
      password: root
      driver-class-name: org.postgresql.Driver

  jpa:
      show-sql: true
      hibernate:
          naming:
              physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html